CREATE TABLE "role_permissions" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "role_id" BIGINT NOT NULL,
    "permission_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_role_permissions_by_role_id" ON "role_permissions" ("role_id");
CREATE INDEX "index_role_permissions_by_permission_id" ON "role_permissions" ("permission_id");
CREATE TABLE "permissions" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_permissions_by_code" ON "permissions" ("code");
CREATE TABLE "users" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_users_by_username" ON "users" ("username");
CREATE TABLE "roles" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_roles_by_name" ON "roles" ("name");
CREATE TABLE "refresh_tokens" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" BIGINT NOT NULL,
    "token" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_refresh_tokens_by_token" ON "refresh_tokens" ("token");
CREATE TABLE "user_roles" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" BIGINT NOT NULL,
    "role_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_user_roles_by_user_id" ON "user_roles" ("user_id");
CREATE INDEX "index_user_roles_by_role_id" ON "user_roles" ("role_id");
